title: Thinh's WebBlog
description: My personal website for sharing knowledge and resources.
theme: just-the-docs

url: https://qth24.github.io

collections:
  docs:
    output: true
    permalink: /:collection/:path/
